# Generated by Django 3.2.2 on 2022-04-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_alter_buyerinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerinfo',
            name='photo',
            field=models.ImageField(blank=True, default='default/default-logo.png', null=True, upload_to=''),
        ),
    ]
