# Generated by Django 3.2.2 on 2022-05-11 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyer', '0008_cart_cartitem_cartshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRecipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transection_id', models.CharField(max_length=20)),
                ('bank_reciept', models.ImageField(upload_to='bank_reciept/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
