# Generated by Django 3.2.2 on 2022-05-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_buyersgippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyersgippingaddress',
            old_name='user',
            new_name='buyer',
        ),
    ]
