# Generated by Django 3.2.2 on 2022-05-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0013_auto_20220516_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
