# Generated by Django 3.2.2 on 2022-06-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0014_cartitem_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
